#
# DgAccelerator plugin PR workflow
# Copyright 2023 DeGirum Corporation
#
# Configure and install dependencies, build plugin, and runs tests
#

name: CI Merge workflow

on:
  # run this action on pull requests to main branch
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, dg-ubuntu-20.04-nv-02]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Configure the build, remove cache if exists
      run: |
        mkdir build 
        cd build
        rm CMakeCache.txt
        cmake ..
    - name: Build the plugin
      run: |
        cd build 
        cmake --build .
    - name: Install the plugin
      run: |
        cd build 
        cmake --install .
    - name: Verify Installation
      run: gst-inspect-1.0 dgaccelerator
