#
# DgAccelerator plugin PR workflow
# Copyright 2023 DeGirum Corporation
#
# Configure and install dependencies, build plugin, and runs tests
#

name: CI Merge workflow

on:
  # run this action on pull requests to main branch
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, dg-ubuntu-20.04-nv-02]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Print working dir
        run: pwd
      - name: Print LD_LIBRARY_PATH
        run: echo $LD_LIBRARY_PATH
      - name: Print all the environment variables
        run: printenv
      - name: Configure the build, remove cache if exists
        run: |
          mkdir build 
          cd build
          rm -f CMakeCache.txt
          cmake ..
      - name: Build the plugin
        run: |
          cd build 
          cmake --build .
      - name: Install the plugin
        run: |
          cd build 
          cmake --install .
      - name: Verify Installation
        run: | 
          export LD_LIBRARY_PATH=/opt/nvidia/deepstream/deepstream/lib/:$LD_LIBRARY_PATH
          gst-inspect-1.0 dgaccelerator
      - name: Run GTests
        run: |
          export PATH=/usr/local/cuda-11.8/bin:$PATH
          export LD_LIBRARY_PATH=/usr/local/cuda-11.8/lib64:$LD_LIBRARY_PATH
          export LD_LIBRARY_PATH=/opt/nvidia/deepstream/deepstream/lib/:$LD_LIBRARY_PATH
          cd build
          ./run_tests